import { FormEvent, useEffect, useMemo, useState } from 'react';
import type { OutboundMessageResult, Platform, PlatformStatus } from '@mstream/contracts';

export function StreamSettings({ statuses }: { statuses: PlatformStatus[] }) {
  const connected = useMemo(() => statuses.filter((status) => status.state === 'connected').map((status) => status.platform), [statuses]);
  const [selected, setSelected] = useState<Platform[]>([]); const [title, setTitle] = useState(''); const [categoryId, setCategoryId] = useState(''); const [results, setResults] = useState<OutboundMessageResult[]>([]);
  useEffect(() => setSelected(connected), [connected.join(',')]);
  async function submit(event: FormEvent) { event.preventDefault(); if ((!title.trim() && !categoryId.trim()) || !selected.length) return; const response = await fetch('/commands/stream', { method: 'PATCH', credentials: 'include', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ title: title.trim() || undefined, categoryId: categoryId.trim() || undefined, destinations: selected }) }); setResults(await response.json() as OutboundMessageResult[]); }
  return <form className="composer" onSubmit={submit} aria-labelledby="stream-settings-title"><h2 id="stream-settings-title">Paramètres du stream</h2><div className="settings-fields"><label>Titre<input value={title} maxLength={140} onChange={(event) => setTitle(event.target.value)} /></label><label>Catégorie / ID<input value={categoryId} onChange={(event) => setCategoryId(event.target.value)} /></label></div><div className="recipient-list">{(['twitch', 'kick'] as const).map((platform) => <label key={platform}><input type="checkbox" checked={selected.includes(platform)} disabled={!connected.includes(platform)} onChange={(event) => setSelected((current) => event.target.checked ? [...current, platform] : current.filter((value) => value !== platform))} /> {platform}</label>)}</div><button type="submit" disabled={(!title.trim() && !categoryId.trim()) || !selected.length}>Mettre à jour</button>{results.length > 0 && <ul className="result-list" aria-live="polite">{results.map((result) => <li key={result.platform}><span>{result.platform}</span><strong>{result.status}</strong>{result.message && <small>{result.message}</small>}</li>)}</ul>}</form>;
}
